services:
  app:
    build: .
  proxy:
    image: 'nginx:latest'
    volumes:
      - '/srv/nginx/ssl:/etc/ssl'
      - '/srv/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
      - '443:443'
