---
- name: Install docker
  hosts: all
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install ca-certificates curl
      apt:
        pkg:
        - ca-certificates
        - curl

    - name: create keyring dir
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: download key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: add docker repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

    - name: install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
