---
- name: Install docker
  hosts: all
  tasks:

    - name: install ca-certificates curl
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - curl

    - name: create keyring dir
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: download key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: add docker repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

    - name: install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: checkout repo
      git:
        repo: https://github.com/dockersamples/linux_tweet_app
        dest: /srv/linux_tweet_app

    - name: build image
      docker_image:
        name: linux_tweet_app
        build:
          path: /srv/linux_tweet_app
        source: build

    - name: create token dir
      file:
        path: /srv/linux_tweet_app/token
        state: directory
        mode: '0755'

    - name: copy test token
      copy:
        src: token.html
        dest: /srv/linux_tweet_app/token.html

    - name: run linux_tweet_app
      docker_container:
        pull: never
        name: linux_tweet_app
        image: linux_tweet_app
        ports:
        - '80:80'
        mounts:
          - type: bind
            source: /srv/linux_tweet_app/token.html
            target: /usr/share/nginx/html/.well-known/acme-challenge/token.html

    - name: create a cert challenge
      acme_certificate:
        account_key_src: /etc/pki/cert/private/account.key
        account_email: igor.d.melnikov62@gmail.com
        csr: /etc/pki/cert/csr/{{ inventory_hostname }}.csr
        fullchain_dest: /etc/ssl/${{ inventory_hostname }}.crt
      register: cert_challenge
