---
- name: Install docker
  hosts: all
  tasks:

    - name: install ca-certificates curl
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - curl

    - name: create keyring dir
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: download key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: add docker repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

    - name: install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: checkout repo
      git:
        repo: https://github.com/dockersamples/linux_tweet_app
        dest: /srv/linux_tweet_app

    - name: build image
      docker_image:
        build:
          path: /srv/linux_tweet_app
          name: linux_tweet_app

    - name: run linux_tweet_app
      docker_cointainer:
        pull: never
        name: linux_tweet_app
        image: linux_tweet_app
        ports:
        - '80:80'
