---
- name: Install docker
  hosts: all
  tasks:

    - name: get package facts
      package_facts:

    - name: skip if installed
      meta: end_play
      when: "'docker-ce' in ansible_facts.packages"

    - name: install ca-certificates curl
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - curl

    - name: create keyring dir
      file:
        path: /etc/apt/keyrings/
        state: directory
        mode: '0755'

    - name: download key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: add docker repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

    - name: install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

- name: Deploy app
  hosts: all
  tasks:

    - name: checkout repo
      git:
        repo: https://github.com/dockersamples/linux_tweet_app
        dest: /srv/linux_tweet_app

    - name: build image
      docker_image:
        name: linux_tweet_app
        build:
          path: /srv/linux_tweet_app
        source: build

    - name: create cert dirs
      file:
        path: /srv/linux_tweet_app/{{ item }}/
        state: directory
        mode: '0600'
      loop:
        - csr
        - ssl

    - name: generate cert key
      openssl_privatekey:
        path: /srv/linux_tweet_app/ssl/{{ inventory_hostname }}.key
        cipher: auto

    - name: list of dns names
      set_fact:
        hostname:
        - '{{ inventory_hostname }}'
        - www.{{ inventory_hostname }}

    - name: create csr
      openssl_csr:
        path: /srv/linux_tweet_app/csr/{{ inventory_hostname }}.csr
        privatekey_path: /srv/linux_tweet_app/ssl/{{ inventory_hostname }}.key
        subject_alt_name: "{{ hostname | map('regex_replace', '^', 'DNS:') | list }}"

    - name: generate acme account key
      openssl_privatekey:
        path: /srv/linux_tweet_app/csr/acme_account.key
        passphrase: '{{ acme_key_passphrase }}'
        cipher: auto

    - name: create a cert challenge
      acme_certificate:
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        terms_agreed: true
        acme_version: 2
        account_key_src: /srv/linux_tweet_app/csr/acme_account.key
        account_key_passphrase: '{{ acme_key_passphrase }}'
        account_email: igor.d.melnikov62@gmail.com
        csr: /srv/linux_tweet_app/csr/{{ inventory_hostname }}.csr
        fullchain_dest: /srv/linux_tweet_app/ssl/{{ inventory_hostname }}.crt
      register: cert_challenge

    - name: create challenge dirs
      file:
        path: /srv/linux_tweet_app/html/{{ item.value['http-01']['resource'] | dirname }}
        state: directory
        mode: '0755'
      loop: '{{ cert_challenge.challenge_data | dict2items }}'
      when: cert_challenge is changed

    - name: copy challenges
      copy:
        dest: /srv/linux_tweet_app/html/{{ item.value['http-01']['resource'] }}
        content: "{{ item.value['http-01']['resource_value'] }}"
      loop: '{{ cert_challenge.challenge_data | dict2items }}'
      when: cert_challenge is changed

    - name: run linux_tweet_app
      docker_container:
        pull: never
        name: linux_tweet_app
        image: linux_tweet_app
        ports:
        - '80:80'
        mounts:
          - type: bind
            source: /srv/linux_tweet_app/html/
            target: /usr/share/nginx/html/

    - name: let challenge be validated
      acme_certificate:
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_version: 2
        account_key_src: /srv/linux_tweet_app/csr/acme_account.key
        account_key_passphrase: '{{ acme_key_passphrase }}'
        csr: /srv/linux_tweet_app/csr/{{ inventory_hostname }}.csr
        fullchain_dest: /srv/linux_tweet_app/ssl/{{ inventory_hostname }}.crt
        data: '{{ cert_challenge }}'

    - name: copy nginx conf
      copy:
        src: nginx.conf
        dest: /srv/linux_tweet_app/nginx.conf

    - name: mount nginx conf
      docker_container:
        pull: never
        name: linux_tweet_app
        image: linux_tweet_app
        ports:
        - '80:80'
        - '443:443'
        mounts:
          - type: bind
            source: /srv/linux_tweet_app/nginx.conf
            target: /etc/nginx/nginx.conf
          - type: bind
            source: /srv/linux_tweet_app/ssl/
            target: /etc/ssl/
