---
- name: Install Docker
  hosts: all
  tasks:

    - name: Get package facts
      package_facts:

    - name: Skip if Docker is installed
      meta: end_play
      when: "'docker-ce' in ansible_facts.packages"

    - name: Install ca-certificates curl
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - curl

    - name: Create keyring dir
      file:
        path: /etc/apt/keyrings/
        state: directory
        mode: '0755'

    - name: Download key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: Add repo
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

    - name: Install packages
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

- name: Provision certs and deploy the app
  hosts: all
  tasks:

    - name: Create reverse proxy dir
      file:
        path: /srv/nginx/ssl
        state: directory
        mode: '0600'

    - name: Generate private cert key
      openssl_privatekey:
        path: /srv/nginx/ssl/{{ inventory_hostname }}.key

    - name: Create list of DNS names
      set_fact:
        hostname:
        - '{{ inventory_hostname }}'
        - www.{{ inventory_hostname }}

    - name: Create certificate signing request
      openssl_csr:
        path: /srv/nginx/{{ inventory_hostname }}.csr
        privatekey_path: /srv/nginx/ssl/{{ inventory_hostname }}.key
        subject_alt_name: "{{ hostname | map('regex_replace', '^', 'DNS:') | list }}"

    - name: Generate ACME account key
      openssl_privatekey:
        path: /srv/nginx/acme_account.key
        passphrase: '{{ acme_key_passphrase }}'
        cipher: auto

    - name: Create cert challenge
      acme_certificate:
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        terms_agreed: true
        acme_version: 2
        account_key_src: /srv/nginx/acme_account.key
        account_key_passphrase: '{{ acme_key_passphrase }}'
        account_email: igor.d.melnikov62@gmail.com
        csr: /srv/nginx/{{ inventory_hostname }}.csr
        fullchain_dest: /srv/nginx/ssl/{{ inventory_hostname }}.crt
      register: cert_challenge

    - name: Create challenge dirs
      file:
        path: /srv/nginx/html/{{ item.value['http-01']['resource'] | dirname }}
        state: directory
        mode: '0755'
      loop: '{{ cert_challenge.challenge_data | dict2items }}'
      when: cert_challenge is changed

    - name: Copy challenges
      copy:
        dest: /srv/nginx/html/{{ item.value['http-01']['resource'] }}
        content: "{{ item.value['http-01']['resource_value'] }}"
      loop: '{{ cert_challenge.challenge_data | dict2items }}'
      when: cert_challenge is changed

    - name: Run nginx with challenges
      docker_container:
        name: challenge-proxy
        image: nginx:latest
        ports:
        - '80:80'
        mounts:
          - type: bind
            source: /srv/nginx/html/
            target: /usr/share/nginx/html/
      when: cert_challenge is changed

    - name: Let challenge be validated
      acme_certificate:
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        acme_version: 2
        account_key_src: /srv/nginx/acme_account.key
        account_key_passphrase: '{{ acme_key_passphrase }}'
        csr: /srv/nginx/{{ inventory_hostname }}.csr
        fullchain_dest: /srv/nginx/ssl/{{ inventory_hostname }}.crt
        data: '{{ cert_challenge }}'
      when: cert_challenge is changed

    - name: Remove nginx with challenges
      docker_container:
        name: challenge-proxy
        state: absent
      when: cert_challenge is changed

    - name: Copy nginx.conf
      template:
        src: nginx.conf.j2
        dest: /srv/nginx/nginx.conf

    - name: Checkout repo
      git:
        repo: https://github.com/dockersamples/linux_tweet_app
        dest: /srv/linux_tweet_app

    - name: Copy docker-compose
      copy:
        src: docker-compose.yml
        dest: /srv/linux_tweet_app/docker-compose.yml

    - name: Start docker-compose
      community.docker.docker_compose_v2:
        project_src: /srv/linux_tweet_app
        recreate: always
      register: output

    - name: Wait 1 sec
      wait_for:
        timeout: 1

    - name: Assert that services are running
      assert:
        that:
          - output['containers'][0]['Name'] == 'linux_tweet_app-app-1'
          - output['containers'][0]['State'] == 'running'
          - output['containers'][1]['Name'] == 'linux_tweet_app-proxy-1'
          - output['containers'][1]['State'] == 'running'
