---
- name: Install docker
  hosts: all
  tasks:

    - name: get package facts
      package_facts:

    - name: skip if installed
      meta: end_play
      when: "'docker-ce' in ansible_facts.packages"

    - name: install ca-certificates curl
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - curl

    - name: create keyring dir
      file:
        path: /etc/apt/keyrings/
        state: directory
        mode: '0755'

    - name: download key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: add docker repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

    - name: install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

- name: Deploy app
  hosts: all
  tasks:

    - name: checkout repo
      git:
        repo: https://github.com/dockersamples/linux_tweet_app
        dest: /srv/linux_tweet_app

    - name: build image
      docker_image:
        name: linux_tweet_app
        build:
          path: /srv/linux_tweet_app
        source: build

    - name: create cert dirs
      file:
        path: '{{ item }}'
        state: directory
        mode: '0600'
      loop:
        - /etc/pki/cert/private/
        - /etc/pki/cert/csr/

    - name: generate csr key
      openssl_privatekey:
        path: /etc/pki/cert/private/${{ inventory_hostname}}.pem
        passphrase: '{{ csr_key_passphrase }}'
        cipher: auto

    - name: create csr
      openssl_csr:
        path: /etc/pki/cert/csr/{{ inventory_hostname }}.csr
        privatekey_path: /etc/pki/cert/private/${{ inventory_hostname}}.pem
        privatekey_passphrase: '{{ csr_key_passphrase }}'
        subject_alt_name: 'DNS:{{ inventory_hostname }},DNS:www.{{ inventory_hostname }}'

    - name: generate account key
      openssl_privatekey:
        path: /etc/pki/cert/private/account.key
        passphrase: '{{ acme_key_passphrase }}'
        cipher: auto

    - name: create a cert challenge
      acme_certificate:
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        terms_agreed: true
        acme_version: 2
        account_key_src: /etc/pki/cert/private/account.key
        account_key_passphrase: '{{ acme_key_passphrase }}'
        account_email: igor.d.melnikov62@gmail.com
        csr: /etc/pki/cert/csr/{{ inventory_hostname }}.csr
        fullchain_dest: /etc/ssl/{{ inventory_hostname }}.crt
      register: cert_challenge

    - name: create html dir
      file:
        path: /srv/linux_tweet_app/html/{{ cert_challenge['challenge_data'][inventory_hostname]['http-01']['resource'] | dirname }}
        state: directory
        mode: '0755'

    - name: copy challenge
      copy:
        dest: /srv/linux_tweet_app/html/{{ cert_challenge['challenge_data'][inventory_hostname]['http-01']['resource'] }}
        content: "{{ cert_challenge['challenge_data'][inventory_hostname]['http-01']['resource_value'] }}"
      when: cert_challenge is changed and inventory_hostname in cert_challenge['challenge_data']

    - name: run linux_tweet_app
      docker_container:
        pull: never
        name: linux_tweet_app
        image: linux_tweet_app
        ports:
        - '80:80'
        mounts:
          - type: bind
            source: /srv/linux_tweet_app/html/
            target: /usr/share/nginx/html/

    - name: let challenge be validated
      acme_certificate:
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_version: 2
        account_key_src: /etc/pki/cert/private/account.key
        account_key_passphrase: '{{ acme_key_passphrase }}'
        csr: /etc/pki/cert/csr/{{ inventory_hostname }}.csr
        fullchain_dest: /etc/ssl/{{ inventory_hostname }}.crt
        data: "{{ cert_challenge }}"
