name: "Terraform"

defaults:
  run:
    working-directory: terraform

on:
  push:
    branches:
      - master
    paths:
      - terraform/**
      - .github/workflows/terraform.yml
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_VAR_hostname: ${{ vars.HOSTNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt --check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
        run: terraform apply -auto-approve tfplan
